### ISSUE TITLE
The ReplaceAll method does not match expectations

### ISSUE THREAD

**Issue by Wenveo** [Noisrev/Noisrev.League.IO.RST#10]
**Describe the bug**
This behavior does not correctly replace the text in each item, but instead replaces it all with **newText**.

https://github.com/Wenveo/Noisrev.League.IO.RST/blob/ca00d9c30517a6e8a93e1d73323ba804c17dbf2a/Noisrev.League.IO.RST/RSTBuilder.cs#L356-L364

Just like:
```
// itemText = "This is a text"
// ReplaceAll("a", "b");
// itemText = "b"
```

**Expected behavior**
Able to correctly replace the text of each item.
```
// itemText = "This is a text"
// ReplaceAll("a", "b");
// itemText = "This is b text"
```

**Comment by KERRAT** [comment]
wow, thx!
It was really bug :D
