### ISSUE TITLE
How i can open like Program?

### ISSUE THREAD

**Issue by Geromo94** [Noisrev/Noisrev.League.IO.RST#2]
Hello, i take dll after compile. How to correct open on EXE? :C

**Comment by Wenveo** [comment]
- Add a Dll file reference to your console or desktop application. 

- Or use the Nuget Package manager, search for the name of the repository, find the Nuget package with the same name as the repository, and install it into your project.


There are some simple instructions in the README file.

https://github.com/Noisrev/Noisrev.League.IO.RST#install 🙄
