### ISSUE TITLE
Rion doesn't work in current league patch

### ISSUE THREAD

**Issue by GuiSaiUwU** [Noisrev/Noisrev.League.IO.RST#4]
when you use Rion to edit text, and save back to use, some text will broken even if you didn't touched them.
example: I edited twitch E name, but everything in settings menu got broken text

**Comment by Wenveo** [comment]
Could you please specifically describe what you have changed or upload a screenshot?
I tested it on both NA and CN servers and did not find broken text.

![image](https://user-images.githubusercontent.com/62750690/195256188-096e628d-1c88-48f1-b976-c5ecebe58cd1.png)
![image](https://user-images.githubusercontent.com/62750690/195256210-3fadbda5-11fc-4ce1-aaf9-3507baa85065.png)
![image](https://user-images.githubusercontent.com/62750690/195256363-00f87f92-a009-497b-b19d-ddfea01637ef.png)
![image](https://user-images.githubusercontent.com/62750690/195256431-66394d88-c58e-4302-ae72-23647db70ead.png)

**Comment by GuiSaiUwU** [comment]
![Contaminar](https://user-images.githubusercontent.com/107002177/196019509-f3c6ee46-3283-4224-8287-7237c9239ce8.png)
![test rion](https://user-images.githubusercontent.com/107002177/196019512-f7b5dfff-6c20-4cb8-af9d-8ada8d7a322f.png)
Note: I used cntrl F to change every ";Contaminar" to ";Test Rion", don't know if that would influence that much
![Screen413](https://user-images.githubusercontent.com/107002177/196019546-2507f56d-6499-485b-9bdc-d0a96dd59044.png)
![Screen414](https://user-images.githubusercontent.com/107002177/196019548-3abc063e-60c5-4694-905a-c7e3fa9e678f.png)
![Screen415](https://user-images.githubusercontent.com/107002177/196019551-85acae9c-1d53-43ae-a5ca-8b2c061964d4.png)
![Screen416](https://user-images.githubusercontent.com/107002177/196019553-3d599cbe-fcd7-4e65-b2e4-b0966c67931b.png)
![Screen417](https://user-images.githubusercontent.com/107002177/196019555-0e4efb04-8a5d-435c-ae9b-f32a389856e9.png)
![Screen418](https://user-images.githubusercontent.com/107002177/196019558-a6a00df8-9f30-4966-811e-5eb9a7f1a638.png)

**Comment by GuiSaiUwU** [comment]
I had a test before with Lee Sin and when I tried to look at the R tooltip just crashed league, one friend had the same issue with broken text, while editing global.es_ES, don't know if that is a thing related to latin languages [mine is pt_BR], but Rion wasn't having any issues before
![Screen411](https://user-images.githubusercontent.com/107002177/196019596-d65f8d88-0df8-405e-bd4e-962d756b4351.png)

**Comment by Wenveo** [comment]
When converting from json to rst, I found cases where the byte with the ending was not equal to 0.
![~0Y1 ROUNH8XF$BS)IM))(9](https://user-images.githubusercontent.com/62750690/196036785-6966ab35-6348-4b89-a851-582a0674df94.png) 



But if I open an RST file and write it out, it doesn't happen that the ending byte is not equal to zero.
![74Q21YAZR%97DW7U)LMJSR6](https://user-images.githubusercontent.com/62750690/196036833-ed010a0f-b287-4c97-95e0-0d67f936c3c9.png)

**Comment by Wenveo** [comment]
This is the simplest fix, and it works just fine.
![image](https://user-images.githubusercontent.com/62750690/196037235-f1f9c2de-4ec2-433d-85b0-07be450d8547.png)

The content remains consistent after multiple conversions through the converter.
![image](https://user-images.githubusercontent.com/62750690/196037217-07fd4e08-22cd-4557-b21b-0b74ccb3137e.png)

Json is same.
![image](https://user-images.githubusercontent.com/62750690/196037365-fe04f871-d817-4f22-8fda-0d8a2ced4de8.png)

and rst
![image](https://user-images.githubusercontent.com/62750690/196037417-4e7e7a3b-e513-4032-b820-e688127ecbb1.png)

**Comment by Wenveo** [comment]
@GuiSaiUwU  The latest version of rion has fixed this bug.  
https://github.com/Noisrev/rion/releases/tag/v0.1.2.23974

If you have no other questions, this issue will be closed in a week.

**Comment by GuiSaiUwU** [comment]
Ok ok if I have any issues again I open another thread <3
